# Generated by Django 5.2.1 on 2025-05-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comments_project_id_alter_comments_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='ID',
            new_name='id',
        ),
    ]
