# Generated by Django 5.2.1 on 2025-05-29 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ID',
            new_name='id',
        ),
    ]
