# Generated by Django 4.2.21 on 2025-05-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.ImageField(upload_to='project_images/media')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
