# Generated by Django 5.2.1 on 2025-05-30 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_image',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.ImageField(upload_to='project_images/media')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
