# Generated by Django 5.2.1 on 2025-05-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_image',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
            ],
        ),
    ]
