# Generated by Django 5.2.1 on 2025-05-29 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_is_fetured'),
        ('project_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_image',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
            preserve_default=False,
        ),
    ]
