# Generated by Django 5.2.1 on 2025-05-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_image', '0002_alter_project_image_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_image',
            old_name='ID',
            new_name='id',
        ),
    ]
