# Generated by Django 5.2.1 on 2025-05-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('user_id', models.IntegerField(null=True)),
                ('project_id', models.IntegerField(null=True)),
            ],
        ),
    ]
