# Generated by Django 5.2.1 on 2025-05-25 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreport',
            old_name='project_id',
            new_name='comment_id',
        ),
    ]
