# Generated by Django 5.2.1 on 2025-05-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user_id',
        ),
    ]
