# Generated by Django 5.2.1 on 2025-05-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_user_id_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='user_id',
        ),
    ]
