# Generated by Django 5.2.1 on 2025-05-30 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('Mphone', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user/imgs')),
                ('Pass', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('donor', 'Donor')], max_length=10)),
                ('Bdate', models.DateField(blank=True, null=True)),
                ('Regist_date', models.DateTimeField(auto_now_add=True)),
                ('Facebook_url', models.TextField(default=None, null=True)),
                ('Country', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
