# Generated by Django 5.2.1 on 2025-05-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_fetured',
            field=models.BooleanField(default=False),
        ),
    ]
