# Generated by Django 4.2.21 on 2025-05-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_facebook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Facebook_url',
            field=models.TextField(default=None, null=True),
        ),
    ]
