# Generated by Django 5.2.1 on 2025-05-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_email_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Bdate',
            new_name='bdate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Facebook_url',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Fname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Lname',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Mphone',
            new_name='mphone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Regist_date',
            new_name='regist_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Pass',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
