# Generated by Django 4.2.21 on 2025-05-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_facebook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Bdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
